# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "PearlBee"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# This should be users if you are using postgres, otherwise leave it
# at user for MySQL
user_table: users

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

session: "YAML"

#Logging
#logger: "file"
#log: "error"
template: "template_toolkit"
engines:
  template:
    template_toolkit:
      encoding: 'utf8'
      start_tag: '[%'
      end_tag:   '%]'
  session:
    YAML:
      session_dir: "/tmp/pearlbee"

plugins:
    DBIC:
        # Toggle comments when switching between postgres and mysql
        default:
          schema_class: PearlBee::Model::Schema
          #dsn: dbi:mysql:PearlBee
          #user: root
          #pass: mysqlpassword
          dsn: dbi:Pg:dbname=pearlbee
          user: pearlbee_user
          password: password
          options:
            RaiseError: 1
            PrintError: 1
            #quote_names: 1
            #mysql_enable_utf8: 1

# Constants
captcha_folder :  'public/captcha/'
covers_folder:    'public/uploads/covers/'
import_folder:    'public/uploads/import/'
images_folder:    'public/uploads/images/'
images_path:      '/uploads/images' 
app_url:          'http://localhost:5000'
email_templates:  'views/emails/'

# Specifics
email_signature:       'The PearlBee Team'
default_email_sender:  'no-reply@pearlbee.com'
welcome_email_subject: 'Welcome to PearlBee!'
posts_on_page:         5
